# Generated by Django 6.1 on 2026-08-20 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, default='Lima', max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('documento_tipo', models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carnet de Extranjeria')], default='dni', max_length=10)),
                ('documento_numero', models.CharField(blank=True, max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
